---
title: Demokratiska Städer
timezone: Europe/Stockholm
collections:
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: false
  themes:
    title: Themes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    excerpt: 
    ingress-text: 
- scope:
    path: ''
    type: resources
  values:
    link: 
    author: 
    excerpt: 
    themes:
    - ''
    - ''
- scope:
    path: ''
    type: posts
  values:
    layout: tool
    categories: 
    excerpt: 
    ingress-text: 
    image: 
    time: 
    costs: 
    difficulty: 
    readmore:
    - headline: Läs mer
      links:
      - title: 
        url: 
    - headline: Testa
      links:
      - title: 
        url: 
    - headline: Kontakt
      links:
      - title: 
        url: 
    quote: 
    source: 
    themes:
    - ''
    - ''
- scope:
    path: ''
    type: themes
  values:
    layout: theme
    ref: 
email: admin@digidemlab.org
logo: "/public/logotyp.png"
permalink: "/:title/"
baseurl: ''
url: http://demokratiskastader.se
author: Digidem Lab
description: Verktyg och metoder för framtidens demokratiska städer.
twitter:
  username: digidemlab
facebook:
  publisher: digidemlab
social:
  links:
  - https://twitter.com/digidemlab
  - https://www.facebook.com/digidemlab
  - https://www.instagram.com/digidemlab/
  - https://github.com/digidemlab/demokratiskastader
markdown: kramdown
exclude:
- ".sass-cache"
- bower_components
- path
sass:
  sass_dir: _sass
plugins:
- jekyll-seo-tag
